name: app-build-action
#推送Tag时触发
on:
  push:
     branches:
      - main  # Change this to your main branch name
jobs:
  build-mac-ios-android:
    runs-on: ubuntu-latest
    steps:
      #签出代码 
      - uses: actions/checkout@v3
        with:
         repository: xiaoyaocz/dart_simple_live  # Change 'username/flutter-app' to the repository containing your Flutter app
         ref: master  # Change this to the branch containing your Flutter app
  
      #设置JAVA环境
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          
      #设置Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          
      #更新Flutter的packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get
      #打包APK
      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release --split-per-abi
      #上传APK至Artifacts
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
      
